### ISSUE TITLE
colcon build fails?

### ISSUE THREAD

**Issue by TE-0048005959** [Xilinx/kria_ros_perception#3]
Hi everyone,
I'm trying to setup evironment on Ubuntu 22.04.02 LTS on Docker container following this page.
https://xilinx.github.io/kria-apps-docs/kr260/build/html/docs/ros2_perception_node/docs/app_deployment.html
When I tried to install simulation in step 5, I got the message below.

> source /opt/ros/humble/setup.bash  # source ROS2 Humble
colcon build

---
Starting >>> perception_2nodes
[0.599s] WARNING:colcon.colcon_ros.task.ament_python.build:Package 'perception_2nodes' doesn't explicitly install a marker in the package index (colcon-ros currently does it implicitly but that fallback will be removed in the future)
--- stderr: perception_2nodes                   
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(

Finished <<< perception_2nodes [1.31s]

---

Then ran simulation as in step 6 but there was nothing on Gazebo window.

> source install/setup.bash  # source the workspace as an overlay
ros2 launch perception_2nodes simulation.launch.py

![image](https://github.com/Xilinx/kria_ros_perception/assets/116867574/c7d03436-5e99-4226-8cd6-811b61a3287f)

I think I couldn't have finished colcon build rightly because there was a warning message, right?
If so, how can I solve it?
I googled about the warning message but I couldn't find any suitable information.
I’m new to both Docker and ROS2.

Finally, my pc's environments is below.
Ubuntu 20.04.6 LTS
Docker version 24.0.2.

Any help would be appreciated.
Best regards,

**Comment by TE-0048005959** [comment]
Sorry, that's not colcon's problem.
It's gazebo's error.
When I launched it, there were some messages below.

-----
MESA: error: Failed to query drm device.
libGL error: glx: failed to create dri3 screen
libGL error: failed to load driver: iris
libGL error: failed to open /dev/dri/renderD128: No such file or directory
libGL error: failed to load driver: i965

----
Then I found this.
https://answers.gazebosim.org/answers/28149/revisions/
So I added a volume option to docker run command and works fine for me.
`-v /dev/dri:/dev/dri`

**Comment by mohammedrafi-sk** [comment]
Hi @Satoski-H 

The warning messages you see from `colcon build` can be safely ignored. 

Great to see that you are using docker for Simulation. 
Could you briefly describe how you are setting up your Docker image for simulation?  It might help others who don't have a host machine with Ubuntu 22.04

**Comment by TE-0048005959** [comment]
Hi @mohammedrafi-sk,

Thank you for your information.

I'm new to docker so I don't think my approach is smart though, I hope it helps.
And more, I haven't connect my pc to my KR260 yet.

---
1. Make work space directory
    mkdir WORK_SPACE

2. Pull Ubuntu22.04 docker image
    docker image pull ubuntu:22.04

3. Run docker image
    docker run -it -e DISPLAY="$DISPLAY" --net host -v <Path to WORK_SPACE>:/WORK_SPACE -v /dev/dri:/dev/dri -w /WORK_SPACE ubuntu:22.04
    
    Check display setting by the following way.
    apt install x11-apps
    xeyes
    If the Xeyes window appears, it is OK.

4. Install some tools
    apt-get update -q
    apt-get upgrade -yq
    apt-get install -yq curl wget git pip bash-completion build-essential lsb-release gnupg2 locales eog
    rm -rf /var/lib/apt/lists/*

5. Execute step 1 of "Environment Setup On Host(x86) Machine(Ubuntu 22.04)" on this page.
    But don't install ros-humble-desktop yet.
    https://xilinx.github.io/kria-apps-docs/kr260/build/html/docs/ros2_perception_node/docs/app_deployment.html

6. Install python tools
    apt update
    apt upgrade
    apt install python3-argcomplete python3-colcon-common-extensions python3-vcstool

7. Install libraries
    apt install libgbm1=22.2.5-0ubuntu0.1~22.04.1

    apt install libglapi-mesa=22.2.5-0ubuntu0.1~22.04.1

8. Install ros-humble-desktop
    apt install -y ros-humble-desktop

9.  Execute the rest of the steps on the Xilinx page.
    Before launching gazebo, set environmental variable.

    export XDG_RUNTIME_DIR=/tmp/runtime-root
    You should write this in .bashrc file.

----

I could run the simulation by those steps.
Don't forget to commit the container before closing it.

**Comment by mohammedrafi-sk** [comment]
Closing the issue as there are no open questions.
